// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v4.25.1
// source: grpc/embosser.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessImageResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text    string `protobuf:"bytes,1,opt,name=Text,proto3" json:"Text,omitempty"`
	Source  string `protobuf:"bytes,2,opt,name=Source,proto3" json:"Source,omitempty"`
	Created int64  `protobuf:"varint,3,opt,name=Created,proto3" json:"Created,omitempty"`
}

func (x *ProcessImageResult) Reset() {
	*x = ProcessImageResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_embosser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessImageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessImageResult) ProtoMessage() {}

func (x *ProcessImageResult) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_embosser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessImageResult.ProtoReflect.Descriptor instead.
func (*ProcessImageResult) Descriptor() ([]byte, []int) {
	return file_grpc_embosser_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessImageResult) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ProcessImageResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ProcessImageResult) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

type EmbossTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string `protobuf:"bytes,1,opt,name=Filename,proto3" json:"Filename,omitempty"`
	Body     []byte `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"`
}

func (x *EmbossTextRequest) Reset() {
	*x = EmbossTextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_embosser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbossTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbossTextRequest) ProtoMessage() {}

func (x *EmbossTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_embosser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbossTextRequest.ProtoReflect.Descriptor instead.
func (*EmbossTextRequest) Descriptor() ([]byte, []int) {
	return file_grpc_embosser_proto_rawDescGZIP(), []int{1}
}

func (x *EmbossTextRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *EmbossTextRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type EmbossTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string              `protobuf:"bytes,1,opt,name=Filename,proto3" json:"Filename,omitempty"`
	Result   *ProcessImageResult `protobuf:"bytes,2,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *EmbossTextResponse) Reset() {
	*x = EmbossTextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_embosser_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmbossTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbossTextResponse) ProtoMessage() {}

func (x *EmbossTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_embosser_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbossTextResponse.ProtoReflect.Descriptor instead.
func (*EmbossTextResponse) Descriptor() ([]byte, []int) {
	return file_grpc_embosser_proto_rawDescGZIP(), []int{2}
}

func (x *EmbossTextResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *EmbossTextResponse) GetResult() *ProcessImageResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_grpc_embosser_proto protoreflect.FileDescriptor

var file_grpc_embosser_proto_rawDesc = []byte{
	0x0a, 0x13, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x6d, 0x62, 0x6f, 0x73, 0x73, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x54,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x22, 0x43, 0x0a, 0x11, 0x45, 0x6d, 0x62, 0x6f, 0x73, 0x73, 0x54, 0x65, 0x78, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x5d, 0x0a, 0x12, 0x45, 0x6d, 0x62, 0x6f, 0x73, 0x73,
	0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x46, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x43, 0x0a, 0x08, 0x45, 0x6d, 0x62, 0x6f, 0x73, 0x73, 0x65,
	0x72, 0x12, 0x37, 0x0a, 0x0a, 0x45, 0x6d, 0x62, 0x6f, 0x73, 0x73, 0x54, 0x65, 0x78, 0x74, 0x12,
	0x12, 0x2e, 0x45, 0x6d, 0x62, 0x6f, 0x73, 0x73, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x45, 0x6d, 0x62, 0x6f, 0x73, 0x73, 0x54, 0x65, 0x78, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x66, 0x6f, 0x6d, 0x75, 0x73, 0x65,
	0x75, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x65, 0x78, 0x74, 0x2d, 0x65, 0x6d, 0x62, 0x6f, 0x73,
	0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_embosser_proto_rawDescOnce sync.Once
	file_grpc_embosser_proto_rawDescData = file_grpc_embosser_proto_rawDesc
)

func file_grpc_embosser_proto_rawDescGZIP() []byte {
	file_grpc_embosser_proto_rawDescOnce.Do(func() {
		file_grpc_embosser_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_embosser_proto_rawDescData)
	})
	return file_grpc_embosser_proto_rawDescData
}

var file_grpc_embosser_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_grpc_embosser_proto_goTypes = []interface{}{
	(*ProcessImageResult)(nil), // 0: ProcessImageResult
	(*EmbossTextRequest)(nil),  // 1: EmbossTextRequest
	(*EmbossTextResponse)(nil), // 2: EmbossTextResponse
}
var file_grpc_embosser_proto_depIdxs = []int32{
	0, // 0: EmbossTextResponse.Result:type_name -> ProcessImageResult
	1, // 1: Embosser.EmbossText:input_type -> EmbossTextRequest
	2, // 2: Embosser.EmbossText:output_type -> EmbossTextResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_embosser_proto_init() }
func file_grpc_embosser_proto_init() {
	if File_grpc_embosser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_embosser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessImageResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_embosser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbossTextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_embosser_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmbossTextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_embosser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_embosser_proto_goTypes,
		DependencyIndexes: file_grpc_embosser_proto_depIdxs,
		MessageInfos:      file_grpc_embosser_proto_msgTypes,
	}.Build()
	File_grpc_embosser_proto = out.File
	file_grpc_embosser_proto_rawDesc = nil
	file_grpc_embosser_proto_goTypes = nil
	file_grpc_embosser_proto_depIdxs = nil
}
