// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: grpc/embosser.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Embosser_EmbossText_FullMethodName = "/Embosser/EmbossText"
)

// EmbosserClient is the client API for Embosser service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmbosserClient interface {
	EmbossText(ctx context.Context, in *EmbossTextRequest, opts ...grpc.CallOption) (*EmbossTextResponse, error)
}

type embosserClient struct {
	cc grpc.ClientConnInterface
}

func NewEmbosserClient(cc grpc.ClientConnInterface) EmbosserClient {
	return &embosserClient{cc}
}

func (c *embosserClient) EmbossText(ctx context.Context, in *EmbossTextRequest, opts ...grpc.CallOption) (*EmbossTextResponse, error) {
	out := new(EmbossTextResponse)
	err := c.cc.Invoke(ctx, Embosser_EmbossText_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmbosserServer is the server API for Embosser service.
// All implementations must embed UnimplementedEmbosserServer
// for forward compatibility
type EmbosserServer interface {
	EmbossText(context.Context, *EmbossTextRequest) (*EmbossTextResponse, error)
	mustEmbedUnimplementedEmbosserServer()
}

// UnimplementedEmbosserServer must be embedded to have forward compatible implementations.
type UnimplementedEmbosserServer struct {
}

func (UnimplementedEmbosserServer) EmbossText(context.Context, *EmbossTextRequest) (*EmbossTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmbossText not implemented")
}
func (UnimplementedEmbosserServer) mustEmbedUnimplementedEmbosserServer() {}

// UnsafeEmbosserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmbosserServer will
// result in compilation errors.
type UnsafeEmbosserServer interface {
	mustEmbedUnimplementedEmbosserServer()
}

func RegisterEmbosserServer(s grpc.ServiceRegistrar, srv EmbosserServer) {
	s.RegisterService(&Embosser_ServiceDesc, srv)
}

func _Embosser_EmbossText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbossTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmbosserServer).EmbossText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Embosser_EmbossText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmbosserServer).EmbossText(ctx, req.(*EmbossTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Embosser_ServiceDesc is the grpc.ServiceDesc for Embosser service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Embosser_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Embosser",
	HandlerType: (*EmbosserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmbossText",
			Handler:    _Embosser_EmbossText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc/embosser.proto",
}
